version: '2.1'
volumes:
  library:
  tvseries:
  movies:
  filebrowser:
services:
  # dat-homeserver:
  #   build: ./dat-homeserver
  #   volumes:
  #     - 'dat:/data/'
  #   network_mode: "host"
  # homebridge:
  #   build: ./homebrdige
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - library:/config
      - tvseries:/tv
      - movies:/movies
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    network_mode: host
    volumes:
      - filebrowser:/database.db
      - tvseries:/srv/tv
      - movies:/srv/movies
